### ISSUE TITLE
SVM model in the given format

### ISSUE THREAD

**Issue by harshithnarra** [svm-abstract-verifier/saver#4]
Is there a way of storing the SVM model in the given format after training it using scikit in python?

ovo
<feature space size>
<number of classes>
<kernel type and parameters>
<class 1> <number of support vectors for class 1>
<class 2> <number of support vectors for class 2>
...
<class N> <number of support vectors for class N>
<alpha coefficients>
<support vectors>
<biases>

**Comment by marco-zanella** [comment]
Sure, you may have a look at our [data collection repository](https://github.com/abstract-machine-learning/data-collection), in particular at the Python scripts for training and exporting models: [https://github.com/abstract-machine-learning/data-collection/blob/master/trainers/classifier_mapper.py](https://github.com/abstract-machine-learning/data-collection/blob/master/trainers/classifier_mapper.py).

**Comment by harshithnarra** [comment]
Thank you, that helped.
