### ISSUE TITLE
I couldn't reach the result in your paper

### ISSUE THREAD

**Issue by louyuteng** [svm-abstract-verifier/saver#7]
Dear Marco Zanella,

Thanks for providing code!!
I have a problem when I execute `bin/saver ../data/mnist/svm-rbf-60k.dat ../data/mnist/test-set-normalized.csv raf l_inf 0.001`

I get `svm-rbf-60k.dat` from `data-collection/domains/mnist/models/svm`
and` test-set-normalized.csv` from `data-collection/domains/mnist/datasets`
  
But I get the result provable robustness for RBF is 99.93%  which is different from the result in  paper "Robustness Verification of Support Vector Machines" table(a) 100.00%

And I also execute `bin/saver ../data/mnist/svm-rbf-60k.dat ../data/mnist/test-set-normalized.csv raf l_inf 0.01`

The test results of the above two are shown below：
|  [SUMMARY]	|  Size  |    Epsilon	 |  Avg.Time (ms)    |    Correct	|  Robust 	  |  Cond. robust |
|  :------------:  | :----:  |  :-----------: |:-------------------:|:----------: |:----------:|:---------------:|
|  [SUMMARY]	 |  10000	|    0.001	  |    721.997413   |    9837	  |  9988	|    9830  |

|  [SUMMARY]	|  Size  |    Epsilon	 |  Avg.Time (ms)    |    Correct	|  Robust 	  |  Cond. robust |
|  :------------:  | :----:  |  :-----------: |:-------------------:|:----------: |:----------:|:---------------:|
|  [SUMMARY]	 |  10000  |   0.01 	|  726.200608	 |   9837	   |       9839  |     9752  |

There is your result：
![image](https://user-images.githubusercontent.com/55194379/143159107-b25fe5e1-aa52-4ad5-89a3-9f15244c9578.png)

Why couldn't I reach the result in your paper?
I'll be waiting for your reply!
louyuteng

**Comment by marco-zanella** [comment]
Dear louyuteng, thank you for your question and sorry for late reply!
This is probably due to a bug we fixed [on April 2020](https://github.com/abstract-machine-learning/saver/commit/c419b05b2d9f7b2a04b38c26a02af36edd8f342a) , where computed lowerbounds for robustness were too high when verifying an RBF kernel with RAF (or hybrid) abstraction.
Results from our paper were affected by that bug, yielding percentages higher than necessary in the aforementioned scenarios. Error is usually higher for greater values of epsilon.

Hope this clarifies a bit, if you need further assistance do not hesitate to ask!

**Comment by louyuteng** [comment]
Dear Marco Zanella,

Thank you for getting back to me !
According to your answer，is my following understanding correct?

when given a trained SVM model  `svm-rbf-60k.dat` from `data-collection/domains/mnist/models/svm`, 
if I use code before fixed bug to verify the robustness of trained SVM, I will get the same result as shown in `table(a)` of your paper.
and if I want to get the correct  result about  verifying the robustness of trained SVM, I should use fixed bug's code to verify.

**Comment by marco-zanella** [comment]
Dear louyuteng,
yes your understanding is indeed correct.

**Comment by louyuteng** [comment]
Dear Marco Zanella,
My problem has been solved. Thank you again for your patience to answer my question!
