### ISSUE TITLE
Completeness and concrete labels

### ISSUE THREAD

**Issue by lambdaxdotx** [svm-abstract-verifier/saver#9]
Hi,

Being an abstract interpreter, SAVer is correct but not complete. Is that the case for the `Concrete` label too, or it is complete in that regard?
Is the `Concrete` label computed by executing the model on the data point?
Could the `Concrete` column display more than one label for a data point (of course, given a perturbation `> 0`)?

Thanks.

**Comment by marco-zanella** [comment]
Hi!
By "concete" we refere to the classifier as a concrete (i.e. not abstract) function, which operates on a single data point. Note that this is the function itself, not is collecting semantics which would operate over sets of points. As such we can't talk about perturbations or "completeness", that applies to abstract transfer functions only.
In words the "concrete" label is the same that you would get from a regular sklearn o libsvm, with the exception that SAVer may show more than one label for a point. This can happen in case of a OVO multi-label classification when two classes share the same maximal score (libsvm and sklearn forcefully return the first one they encounter, instead).
I'll mark the issue as "closed" for now, but feel free to reopen if you have further questions!

**Comment by lambdaxdotx** [comment]
Thanks for your answer.
